sellAtTarget = 1.015
buyAtTarget = 0.975
stopLoss = true

 # if loss >= 5% then sell
stopLossSellAt = 1.05

 # set fallse to strat from sell asset
toBuyAtStart = true

# if other than 0 then buy/sell @ fixedPrice (atStart)
fixedDirectPrice = 0 